"""Add visitor management tables

Revision ID: c36b5bd18601
Revises: c2488eaf3392
Create Date: 2025-11-05 12:33:04.217362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c36b5bd18601'
down_revision: Union[str, None] = 'c2488eaf3392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('id_number', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('purpose', sa.String(length=200), nullable=False),
    sa.Column('expected_arrival', sa.DateTime(), nullable=False),
    sa.Column('expected_departure', sa.DateTime(), nullable=True),
    sa.Column('host_name', sa.String(length=100), nullable=False),
    sa.Column('host_contact', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=True),
    sa.Column('blacklist_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_visitors_email', 'visitors', ['email'], unique=False)
    op.create_index('idx_visitors_expected_arrival', 'visitors', ['expected_arrival'], unique=False)
    op.create_index('idx_visitors_phone', 'visitors', ['phone'], unique=False)
    op.create_index('idx_visitors_status', 'visitors', ['status'], unique=False)
    op.create_table('visitor_passes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visitor_id', sa.Integer(), nullable=False),
    sa.Column('gate_id', sa.Integer(), nullable=False),
    sa.Column('qr_code_data', sa.Text(), nullable=False),
    sa.Column('qr_image', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gate_id'], ['gates.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_visitor_passes_expires_at', 'visitor_passes', ['expires_at'], unique=False)
    op.create_index('idx_visitor_passes_gate_id', 'visitor_passes', ['gate_id'], unique=False)
    op.create_index('idx_visitor_passes_visitor_id', 'visitor_passes', ['visitor_id'], unique=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'endpoint',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('audit_logs', 'session_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_logs_session', 'audit_logs', ['session_id'], unique=False)
    op.create_index('idx_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('idx_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.add_column('logs', sa.Column('visitor_pass_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'logs', 'visitor_passes', ['visitor_pass_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logs', type_='foreignkey')
    op.drop_column('logs', 'visitor_pass_id')
    op.drop_index('idx_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_logs_session', table_name='audit_logs')
    op.drop_index('idx_audit_logs_entity', table_name='audit_logs')
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.alter_column('audit_logs', 'session_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('audit_logs', 'endpoint',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index('idx_visitor_passes_visitor_id', table_name='visitor_passes')
    op.drop_index('idx_visitor_passes_gate_id', table_name='visitor_passes')
    op.drop_index('idx_visitor_passes_expires_at', table_name='visitor_passes')
    op.drop_table('visitor_passes')
    op.drop_index('idx_visitors_status', table_name='visitors')
    op.drop_index('idx_visitors_phone', table_name='visitors')
    op.drop_index('idx_visitors_expected_arrival', table_name='visitors')
    op.drop_index('idx_visitors_email', table_name='visitors')
    op.drop_table('visitors')
    # ### end Alembic commands ###
