"""Add visitor management tables

Revision ID: c36b5bd18601
Revises: c2488eaf3392
Create Date: 2025-11-05 12:33:04.217362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c36b5bd18601'
down_revision: Union[str, None] = 'c2488eaf3392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add visitor_pass_id column to logs table (tables already exist from manual creation)
    op.add_column('logs', sa.Column('visitor_pass_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'logs', 'visitor_passes', ['visitor_pass_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logs', type_='foreignkey')
    op.drop_column('logs', 'visitor_pass_id')
    op.drop_index('idx_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_logs_session', table_name='audit_logs')
    op.drop_index('idx_audit_logs_entity', table_name='audit_logs')
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.alter_column('audit_logs', 'session_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('audit_logs', 'endpoint',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('audit_logs', 'entity_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index('idx_visitor_passes_visitor_id', table_name='visitor_passes')
    op.drop_index('idx_visitor_passes_gate_id', table_name='visitor_passes')
    op.drop_index('idx_visitor_passes_expires_at', table_name='visitor_passes')
    op.drop_table('visitor_passes')
    op.drop_index('idx_visitors_status', table_name='visitors')
    op.drop_index('idx_visitors_phone', table_name='visitors')
    op.drop_index('idx_visitors_expected_arrival', table_name='visitors')
    op.drop_index('idx_visitors_email', table_name='visitors')
    op.drop_table('visitors')
    # ### end Alembic commands ###
